apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: cloudstream-dev
data:
  APP_ENV: "dev"
  PORT: "8000"
  KAFKA_TOPIC: "orders"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"