containers:
- name: api-service
  image: cloudstreamacrshivani001.azurecr.io/api-service:v3
  imagePullPolicy: Always
  ports:
  - containerPort: 3000
  env:
  - name: FUNCTION_URL
    value: "https://cloudstream-order-function.azurewebsites.net/api/orderNotification"
  envFrom:
  - configMapRef:
      name: api-config
  - secretRef:
      name: api-secret