apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: cloudstream-dev

spec:
  provider: azure

  parameters:
    clientID: "10bb3bde-6c60-42a3-a6f3-78446eb08e17"
    keyvaultName: "kv-cloudstream-dev"
    tenantId: "71ec65fa-0ffc-43f0-8721-efc1424b5760"

    objects: |
      array:
        - |
          objectName: eventhub-connection-string-v2
          objectType: secret
        - |
          objectName: appinsights-connection-string
          objectType: secret

  secretObjects:
    - secretName: cloudstream-secrets
      type: Opaque
      data:
        - objectName: eventhub-connection-string-v2
          key: EVENT_HUB_CONNECTION_STRING

        - objectName: appinsights-connection-string
          key: APPLICATIONINSIGHTS_CONNECTION_STRING