apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-service
  namespace: cloudstream-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker-service

  template:
    metadata:
      labels:
        app: worker-service

    spec:
      containers:
      - name: worker-service
        image: cloudstreamacrshivani001.azurecr.io/worker-service:v2
        imagePullPolicy: Always

        env:
        - name: FUNCTION_URL
          value: "https://cloudstream-order-function.azurewebsites.net/api/orderNotification"

        - name: EVENTHUB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: eventhub-secret
              key: EVENTHUB_CONNECTION_STRING

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"