apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudstream-tls
  namespace: cloudstream-prod
spec:
  secretName: cloudstream-tls-secret

  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer

  commonName: api.cloudstream.local

  dnsNames:
  - api.cloudstream.local
