jobs:
- job: BuildFunction
  steps:
  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: processor-function
      dockerfile: src/processor-function/Dockerfile
      containerRegistry: acr-service-connection
      tags: |
        $(imageTag)
        latest
