jobs:
- job: BuildAPI
  steps:
  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: api-service
      dockerfile: src/api-service/Dockerfile
      containerRegistry: azure-service-connection-new
      tags: |
        $(imageTag)
        latest
