jobs:
- job: DeployToAKS

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: azure-service-connection-new
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |

        az aks get-credentials \
          --resource-group rg-cloudstream-dev \
          --name aks-cloudstream-dev \
          --overwrite-existing

        kubectl apply -f manifests/base/api-deployment.yaml
        kubectl apply -f manifests/base/api-service.yaml
        kubectl apply -f manifests/base/api-hpa.yaml

        kubectl apply -f manifests/base/worker-deployment.yaml

        kubectl set image deployment/api-service \
          api-service=cloudstreamacrshivani001.azurecr.io/api-service:$(Build.BuildId) \
          -n cloudstream-dev

        kubectl set image deployment/worker-service \
          worker-service=cloudstreamacrshivani001.azurecr.io/worker-service:$(Build.BuildId) \
          -n cloudstream-dev

        kubectl rollout status deployment/api-service \
          -n cloudstream-dev

        kubectl rollout status deployment/worker-service \
          -n cloudstream-dev