trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: myacrcloudstream123
  acrLoginServer: myacrcloudstream123.azurecr.io
  imageTag: $(Build.BuildId)

stages:
- stage: BuildAPI
  jobs:
  - template: templates/build-api.yml

- stage: BuildFunction
  dependsOn: BuildAPI
  jobs:
  - template: templates/build-function.yml

- stage: Deploy
  dependsOn: BuildFunction
  jobs:
  - template: templates/deploy-aks.yml
