trigger:

* main

pool:
vmImage: ubuntu-latest

variables:
imageTag: $(Build.BuildId)

stages:

* stage: BuildAPI
  jobs:

  * template: azure-pipelines/templates/build-api.yml

* stage: BuildWorker
  dependsOn: BuildAPI
  jobs:

  * template: azure-pipelines/templates/build-worker.yml

* stage: DeployDEV
  dependsOn:

  * BuildAPI
  * BuildWorker
    jobs:
  * template: azure-pipelines/templates/deploy-aks.yml
