trigger:
  branches:
    include:
      - main

variables:
  acrName: cloudstreamacrshivani001
  imageTag: $(Build.BuildId)

stages:

# ==========================================
# BUILD
# ==========================================
- stage: Build
  displayName: Build

  jobs:

  - job: Build_API
    displayName: Build API Image

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      displayName: Build and Push API Image
      inputs:
        command: buildAndPush
        repository: api-service
        dockerfile: src/api-service/Dockerfile
        containerRegistry: acr-service-connection
        tags: |
          $(imageTag)

  - job: Build_Worker
    displayName: Build Worker Image

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      displayName: Build and Push Worker Image
      inputs:
        command: buildAndPush
        repository: worker-service
        dockerfile: src/worker-service/Dockerfile
        containerRegistry: acr-service-connection
        tags: |
          $(imageTag)

# ==========================================
# DEV
# ==========================================
- stage: DEV
  displayName: DEV
  dependsOn: Build

  jobs:

  - deployment: Deploy_DEV
    displayName: Deploy DEV
    environment: cloudstream-dev

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: KubernetesManifest@1
            displayName: Deploy to DEV
            inputs:
              action: deploy
              kubernetesServiceConnection: aks-dev-service-connection
              namespace: cloudstream-dev
              manifests: |
                manifests/base/api-configmap.yaml
                manifests/base/api-deployment.yaml
                manifests/base/api-hpa.yaml
                manifests/base/api-sa.yaml
                manifests/base/api-secret.yaml
                manifests/base/api-service.yaml
                manifests/base/azure-kv-secrets.yaml
                manifests/base/worker-deployment.yaml
                manifests/base/ingress.yaml
                

# ==========================================
# UAT
# ==========================================
- stage: UAT
  displayName: UAT
  dependsOn: DEV

  jobs:

  - deployment: Deploy_UAT
    displayName: Deploy UAT
    environment: cloudstream-uat

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: KubernetesManifest@1
            displayName: Deploy to UAT
            inputs:
              action: deploy
              kubernetesServiceConnection: aks-uat-service-connection
              namespace: cloudstream-uat
              manifests: |
                manifests/uat/api-deployment.yaml
                manifests/uat/api-service.yaml
                manifests/uat/api-hpa.yaml
                manifests/uat/azure-kv-secrets.yaml
                manifests/uat/worker-deployment.yaml
                manifests/uat/ingress.yaml

# ==========================================
# PROD
# ==========================================
- stage: PROD
  displayName: PROD
  dependsOn: UAT

  jobs:

  - deployment: Deploy_PROD
    displayName: Deploy PROD
    environment: cloudstream-prod

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: KubernetesManifest@1
            displayName: Deploy to PROD
            inputs:
              action: deploy
              kubernetesServiceConnection: aks-prod-service-connection
              namespace: cloudstream-prod
              manifests: |
                manifests/prod/api-configmap.yaml
                manifests/prod/api-deployment.yaml
                manifests/prod/api-hpa.yaml
                manifests/prod/api-sa.yaml
                manifests/prod/api-secret.yaml
                manifests/prod/api-service.yaml
                manifests/prod/azure-kv-secrets.yaml
                manifests/prod/worker-deployment.yaml
                manifests/prod/worker-sa.yaml
                manifests/prod/ingress.yaml